name: elk-opensearch

networks:
  opensearch-network:
    name: opensearch-network
    driver: bridge

volumes:
  opensearch-data:
    name: opensearch-data
  opensearch-dashboards-data:
    name: opensearch-dashboards-data
  opensearch-filebeat-data:
    name: opensearch-filebeat-data

services:
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.19.3
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    volumes:
      # docker run --rm opensearchproject/opensearch:2.19.3 cat /usr/share/opensearch/config/opensearch.yml > ./opensearch/config/opensearch.yml
      - ./volumes/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-network
    mem_limit: 2g

  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:2.19.3
    ports:
      - 5601:5601
    volumes:
      # docker run --rm opensearchproject/opensearch-dashboards:2.19.3 cat /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml > ./opensearch-dashboards/config/opensearch_dashboards.yml
      - ./volumes/opensearch-dashboards/config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - opensearch-dashboards-data:/usr/share/opensearch-dashboards/data
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - opensearch-network
    depends_on:
      - opensearch

  opensearch-logstash:
    container_name: opensearch-logstash
    image: opensearch-logstash
    build:
      context: .
      dockerfile: Dockerfile.logstash
    ports:
      - 5044:5044 # Beats input (Filebeat, etc.)
      - 8080:8080 # HTTP input (REST)
    volumes:
     - ./volumes/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
     - ./volumes/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - opensearch-network
    depends_on:
      - opensearch
  
  opensearch-filebeat:
    container_name: opensearch-filebeat
    image: elastic/filebeat:9.1.4
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - opensearch-filebeat-data:/usr/share/filebeat/data
    networks:
      - opensearch-network
    depends_on:
      - opensearch-logstash
